class Acronym:
    def __init__(self, acronym, stands_for):
        self.acronym = acronym
        self.stands_for = stands_for

all_acronyms = [
      Acronym("3DES", "Triple Digital Encryption Standard"),
      Acronym("AAA", "Authentication, Authorization, and Accounting"),
      Acronym("ABAC", "Attribute-based Access Control"),
      Acronym("ACL", "Access Control List"),
      Acronym("AES", "Advanced Encryption Standard"),
      Acronym("AES256", "Advanced Encryption Standards 256bit"),
      Acronym("AH", "Authentication Header"),
      Acronym("ALE", "Annualized Loss Expectancy"),
      Acronym("AP", "Access Point"),
      Acronym("API", "Application Programming Interface"),
      Acronym("APT", "Advanced Persistent Threat"),
      Acronym("ARO", "Annualized Rate of Occurrence"),
      Acronym("ARP", "Address Resolution Protocol"),
      Acronym("ASLR", "Address Space Layout Randomization"),
      Acronym("ASP", "Application Service Provider"),
      Acronym("AUP", "Acceptable Use Policy"),
      Acronym("AV", "Antivirus"),
      Acronym("BAC", "Business Availability Center"),
      Acronym("BCP", "Business Continuity Planning"),
      Acronym("BIA", "Business Impact Analysis"),
      Acronym("BIOS", "Basic Input/Output System"),
      Acronym("BPA", "Business Partners Agreement"),
      Acronym("BPDU", "Bridge Protocol Data Unit"),
      Acronym("BYOD", "Bring Your Own Device"),
      Acronym("CA", "Certificate Authority"),
      Acronym("CAC", "Common Access Card"),
      Acronym("CAN", "Controller Area Network"),
      Acronym("CAPTCHA", "Completely Automated Public Turing test to tell Computers and Humans Apart"),
      Acronym("CAR", "Corrective Action Report"),
      Acronym("CBC", "Cipher Block Chaining"),
      Acronym("CCMP", "Counter-Mode/CBC-Mac Protocol"),
      Acronym("CCTV", "Closed-circuit Television"),
      Acronym("CER", "Certificate"),
      Acronym("CERT", "Computer Emergency Response Team"),
      Acronym("CFB", "Cipher Feedback"),
      Acronym("CHAP", "Challenge Handshake Authentication Protocol"),
      Acronym("CIO", "Chief Information Officer"),
      Acronym("CIRT", "Computer Incident Response Team"),
      Acronym("CMS", "Content Management System"),
      Acronym("COOP", "Continuity of Operation Plan"),
      Acronym("COPE", "Corporate Owned, Personally Enabled"),
      Acronym("CP", "Contingency Planning"),
      Acronym("CRC", "Cyclical Redundancy Check"),
      Acronym("CRL", "Certificate Revocation List"),
      Acronym("CSO", "Chief Security Officer"),
      Acronym("CSP", "Cloud Service Provider"),
      Acronym("CSR", "Certificate Signing Request"),
      Acronym("CSRF", "Cross-site Request Forgery"),
      Acronym("CSU", "Channel Service Unit"),
      Acronym("CTM", "Counter-Mode"),
      Acronym("CTO", "Chief Technology Officer"),
      Acronym("CYOD", "Choose Your Own Device"),
      Acronym("DAC", "Discretionary Access Control"),
      Acronym("DBA", "Database Administrator"),
      Acronym("DDoS", "Distributed Denial of Service"),
      Acronym("DEP", "Data Execution Prevention"),
      Acronym("DER", "Distinguished Encoding Rules"),
      Acronym("DES", "Digital Encryption Standard"),
      Acronym("DHCP", "Dynamic Host Configuration Protocol"),
      Acronym("DHE", "Data Handling Electronics or Diffie-Hellman Ephemeral"),
      Acronym("DLL", "Dynamic Link Library"),
      Acronym("DLP", "Data Loss Prevention"),
      Acronym("DMZ", "Demilitarized Zone"),
      Acronym("DNAT", "Destination Network Address Transaction"),
      Acronym("DNS", "Domain Name Service (Server)"),
      Acronym("DoS", "Denial of Service"),
      Acronym("DRP", "Disaster Recovery Plan"),
      Acronym("DSA", "Digital Signature Algorithm"),
      Acronym("DSL", "Digital Subscriber Line"),
      Acronym("DSU", "Data Service Unit"),
      Acronym("EAP", "Extensible Authentication Protocol"),
      Acronym("ECB", "Electronic Code Book"),
      Acronym("ECC", "Elliptic Curve Cryptography"),
      Acronym("ECDHE", "Elliptic Curve Diffie-Hellman Ephemeral"),
      Acronym("ECDSA", "Elliptic Curve Digital Signature Algorithm"),
      Acronym("EFS", "Encrypted File System"),
      Acronym("EMI", "Electromagnetic Interference"),
      Acronym("EMP", "Electro Magnetic Pulse"),
      Acronym("ERP", "Enterprise Resource Planning"),
      Acronym("ESN", "Electronic Serial Number"),
      Acronym("ESP", "Encapsulated Security Payload"),
      Acronym("FACL", "File System Access Control List"),
      Acronym("FDE", "Full Disk Encryption"),
      Acronym("FRR", "False Rejection Rate"),
      Acronym("FTP", "File Transfer Protocol"),
      Acronym("FTPS", "Secured File Transfer Protocol"),
      Acronym("GCM", "Galois Counter Mode"),
      Acronym("GPG", "Gnu Privacy Guard"),
      Acronym("GPO", "Group Policy Object"),
      Acronym("GPS", "Global Positioning System"),
      Acronym("GPU", "Graphic Processing Unit"),
      Acronym("GRE", "Generic Routing Encapsulation"),
      Acronym("HA", "High Availability"),
      Acronym("HDD", "Hard Disk Drive"),
      Acronym("HIDS", "Host-based Intrusion Detection System"),
      Acronym("HIPS", "Host-based Intrusion Prevention System"),
      Acronym("HMAC", "Hashed Message Authentication Code"),
      Acronym("HOTP", "HMAC-based One-Time Password"),
      Acronym("HSM", "Hardware Security Module"),
      Acronym("HTML", "Hypertext Markup Language"),
      Acronym("HTTP", "Hypertext Transfer Protocol"),
      Acronym("HTTPS", "Hypertext Transfer Protocol over SSL/TLS"),
      Acronym("HVAC", "Heating, Ventilation and Air Conditioning"),
      Acronym("IaaS", "Infrastructure as a Service"),
      Acronym("ICMP", "Internet Control Message Protocol"),
      Acronym("ICS", "Industrial Control Systems"),
      Acronym("ID", "Identification"),
      Acronym("IDEA", "Internation Data Encryption Algorithm"),
      Acronym("IDF", "Intermediate Distribution Frame"),
      Acronym("IdP", "Identity Provider"),
      Acronym("IDS", "Intrusion Detection System"),
      Acronym("IEEE", "Institute of Electrical and Electronic Engineers"),
      Acronym("IKE", "Internet Key Exchange"),
      Acronym("IM", "Instant Messaging"),
      Acronym("IMAP4", "Internet Message Access Protocol v4"),
      Acronym("IoT", "Internet of Things"),
      Acronym("IP", "Internet Protocol"),
      Acronym("IPSec", "Internet Protocol Security"),
      Acronym("IR", "Infrared or Incident Response"),
      Acronym("IRC", "Internet Relay Chat"),
      Acronym("IRP", "Incident Response Plan"),
      Acronym("ISA", "Interconnection Security Agreement"),
      Acronym("ISP", "Internet Service Provider"),
      Acronym("ISSO", "Information Systems Security Officer"),
      Acronym("ITCP", "IT Contingency Plan"),
      Acronym("IV", "Initialization Vector"),
      Acronym("KDC", "Key Distribution Center"),
      Acronym("KEK", "Key Encryption Key"),
      Acronym("L2TP", "Layer 2 Tunneling Protocol"),
      Acronym("LAN", "Local Area Network"),
      Acronym("LDAP", "Lightweight Directory Access Protocol"),
      Acronym("LEAP", "Lightweight Extensible Authentication Protocol"),
      Acronym("MaaS", "Monitoring as a Service"),
      Acronym("MAC", "Mandatory Access Control or Media Access Control or Message Authentication Code"),
      Acronym("MAN", "Metropolitan Area Network"),
      Acronym("MBR", "Master Boot Record"),
      Acronym("MD5", "Message Digest 5"),
      Acronym("MDF", "Main Distribution Frame"),
      Acronym("MFD", "Multi-function Device"),
      Acronym("MITM", "Man-in-the-Middle"),
      Acronym("MMS", "Multimedia Message Service"),
      Acronym("MOA", "Memorandum of Agreement"),
      Acronym("MOU", "Memorandum of Understanding"),
      Acronym("MPLS", "Multi-protocol Label Switching"),
      Acronym("MSCHAP", "Microsoft Challenge Handshake Authentication Protocol"),
      Acronym("MSP", "Managed Service Provider"),
      Acronym("MTBF", "Mean Time Between Failures"),
      Acronym("MTTF", "Mean Time to Failure"),
      Acronym("MTTR", "Mean Time to Recover or Mean Time to Repair"),
      Acronym("MTU", "Maximum Transmission"),
      Acronym("NAC", "Network Access Control"),
      Acronym("NAT", "Network Address Translation"),
      Acronym("NDA", "Non-disclosure Agreement"),
      Acronym("NFC", "Near Fear Communication"),
      Acronym("NIDS", "Network-based Intrusion Detection System"),
      Acronym("NIPS", "Network-based Intrusion Prevention System"),
      Acronym("NIST", "National Institute of Standards & Technology"),
      Acronym("NTFS", "New Technology File System"),
      Acronym("NTLM", "New Technology LAN Manager"),
      Acronym("NTP", "Network Time Protocol"),
      Acronym("OAUTH", "Open Authorization"),
      Acronym("OCSP", "Online Certificate Status Protocol"),
      Acronym("OID", "Object Identifier"),
      Acronym("OS", "Operating System"),
      Acronym("OTA", "Over The Air"),
      Acronym("OVAL", "Open Vulnerability Assessment Language"),
      Acronym("P12", "PKCS #12"),
      Acronym("P2P", "Peer to Peer"),
      Acronym("PaaS", "Platform as a Service"),
      Acronym("PAC", "Proxy Auto Configuration"),
      Acronym("PAM", "Pluggable Authentication Modules"),
      Acronym("PAP", "Password Authentication Protocol"),
      Acronym("PAT", "Port Address Translation"),
      Acronym("PBKDF2", "Password-based Key Dervation Function 2"),
      Acronym("PBX", "Private Branch Exchange"),
      Acronym("PCAP", "Packet Capture"),
      Acronym("PEAP", "Protected Extensible Authentication Protocol"),
      Acronym("PED", "Personal Electronic Device"),
      Acronym("PEM", "Privacy-enhanced Electronic Mail"),
      Acronym("PFS", "Perfect Forward Secrecy"),
      Acronym("PFX", "Personal Exchange Format"),
      Acronym("PGP", "Pretty Good Privacy"),
      Acronym("PHI", "Personal Health Information"),
      Acronym("PII", "Personally Identifiable Information"),
      Acronym("PIV", "Personal Identity Verification"),
      Acronym("PKI", "Public Key Infrastructure"),
      Acronym("POP", "Post Office Protocol"),
      Acronym("POTS", "Plain Old Telephone Service"),
      Acronym("PPP", "Point-to-Point Protocol"),
      Acronym("PPTP", "Point-to-Point Tunneling Protocol"),
      Acronym("PSK", "Pre-shared Key"),
      Acronym("PTZ", "Pan-Tilt-Zoom"),
      Acronym("RA", "Recovery Agent or Registration Authority"),
      Acronym("RAD", "Rapid Application Development"),
      Acronym("RADIUS", "Remote Authentication Dial-in User Server"),
      Acronym("RAID", "Redundant Array of Inexpensive Disks"),
      Acronym("RAS", "Remote Access Server"),
      Acronym("RAT", "Remote Access Trojan"),
      Acronym("RBAC", "Role-based Access Control or Rule-based Access Control"),
      Acronym("RC4", "Rivest Cipher version 4"),
      Acronym("RFID", "Radio Frequency Identifier"),
      Acronym("RIPEMD", "RACE Integrity Primitives Evaluation Message Digest"),
      Acronym("ROI", "Return on Investment"),
      Acronym("RPO", "Recovery Point Objective"),
      Acronym("RSA", "Rivest, Shamir, & Adleman"),
      Acronym("RTBH", "Remotely Triggered Black Hole"),
      Acronym("RTO", "Recover Time Objective"),
      Acronym("RTOS", "Real-time Operating System"),
      Acronym("RTP", "Real-time Transport Protocol"),
      Acronym("S/MIME", "Secure/Multipurpose Internet Mail Extensions"),
      Acronym("SaaS", "Software as a Service"),
      Acronym("SAML", "Security Assertions Markup Language"),
      Acronym("SAN", "Storage Area Network or Subject Alternative Name"),
      Acronym("SCADA", "System Control and Data Acquisition"),
      Acronym("SCAP", "Security Content Automation Protocol"),
      Acronym("SCEP", "Security Certificate Enrollment Protocol"),
      Acronym("SCSI", "Small Computer System Interface"),
      Acronym("SDK", "Software Development Kit"),
      Acronym("SDLC", "Software Development Life Cycle"),
      Acronym("SDLM", "Software Development Life Cycle Methodology"),
      Acronym("SDN", "Software Defined Network"),
      Acronym("SED", "Self-encrypting Drive"),
      Acronym("SEH", "Structured Exception Handler"),
      Acronym("SFTP", "Secured File Transfer Protocol"),
      Acronym("SHA", "Secure Hashing Algorithm"),
      Acronym("SHTTP", "Secure Hypertext Transfer Protocol"),
      Acronym("SIEM", "Security Information and Event Management"),
      Acronym("SIM", "Subscriber Identity Module"),
      Acronym("SLA", "Service Level Agreement"),
      Acronym("SLE", "Single Loss Expectancy"),
      Acronym("SMS", "Short Message Service"),
      Acronym("SMTP", "Simple Mail Transfer Protocol"),
      Acronym("SMTPS", "Simple Mail Transfer Protocol Structure"),
      Acronym("SNMP", "Simple Network Management Protocol"),
      Acronym("SOAP", "Simple Object Access Protocol"),
      Acronym("SoC", "System on Chip"),
      Acronym("SPIM", "Spam over Internet Messaging"),
      Acronym("SQL", "Structured Query Language"),
      Acronym("SRTP", "Secure Real-Time Protocol"),
      Acronym("SSD", "Solid State Drive"),
      Acronym("SSH", "Secure Shell"),
      Acronym("SSL", "Secure Sockets Layer"),
      Acronym("SSO", "Single Sign-on"),
      Acronym("STP", "Shielded Twisted Pair"),
      Acronym("TACACS+", "Terminal Access Controller Access Control System Plus"),
      Acronym("TCP/IP", "Transmission Control Protocol/Internet Protocol"),
      Acronym("TGT", "Ticket Granting Ticket"),
      Acronym("TKIP", "Temporal Key Integrity Protocol"),
      Acronym("TLS", "Transport Layer Security"),
      Acronym("TOTP", "Time-base One-time Password"),
      Acronym("TPM", "Trusted Platform Module"),
      Acronym("TSIG", "Transaction Signature"),
      Acronym("UAT", "User Acceptance Testing"),
      Acronym("UAV", "Unmanned Aerial Vehicle"),
      Acronym("UDP", "User Datagram Protocol"),
      Acronym("UEFI", "Unified Extensible Firmware Interface"),
      Acronym("UPS", "Uninterruptable Power Supply"),
      Acronym("URI", "Uniform Resource Identifier"),
      Acronym("URL", "Universal Resource Locator"),
      Acronym("USB", "Universal Serial Bus"),
      Acronym("USB OTG", "USB On The Go"),
      Acronym("UTM", "Unified Threat Management"),
      Acronym("UTP", "Unshielded Twisted Pair"),
      Acronym("VDE", "Virtual Desktop Environment"),
      Acronym("VDI", "Virtual Desktop Infrastructure"),
      Acronym("VLAN", "Virtual Local Area Network"),
      Acronym("VLSM", "Variable Length Subnet Masking"),
      Acronym("VM", "Virtual Maching"),
      Acronym("VoIP", "Voice over IP"),
      Acronym("VPN", "Virtual Private Network"),
      Acronym("VTC", "Video Teleconferencing"),
      Acronym("WAF", "Web Application Firewall"),
      Acronym("WAP", "Wireless Access Point"),
      Acronym("WEP", "Wired Equivalent Privacy"),
      Acronym("WIDS", "Wireless Intrusion Detection System"),
      Acronym("WIPS", "Wireless Intrusion Prevention System"),
      Acronym("WORM", "Write Once Read Many"),
      Acronym("WPA", "WiFi Protected Access"),
      Acronym("WPA2", "WiFi Protected Access 2"),
      Acronym("WPS", "WiFi Protected Setup"),
      Acronym("WTLS", "Wireless TLS"),
      Acronym("XML", "Extensible Markup Language"),
      Acronym("XOR", "Exclusive Or"),
      Acronym("XSRF", "Cross-site Request Forgery"),
      Acronym("XSS", "Cross-site Scripting"),
      ]


